import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked, type Token } from 'marked';

export interface DocMeta {
  path: string; // 'wiki/gc-logistics.md'
  name: string; // 'wiki/gc-logistics'
  title: string;
  summary: string;
  date: string;
  cert: 'human' | 'hitl' | null;
  tokens: Token[];
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = path.resolve(HERE, '../content');
const OUT_FILE = path.resolve(HERE, '../src/generated/content.ts');

function parseDoc(rel: string): DocMeta {
  const md = fs.readFileSync(path.join(CONTENT_DIR, rel), 'utf8');
  const meta: Record<string, string> = {};
  const body = md.replace(/^(?:[ \t]*<!--\s*\w+:\s*.*?\s*-->\n?)+/, (lead) => {
    for (const m of lead.matchAll(/<!--\s*(\w+):\s*(.*?)\s*-->/g)) meta[m[1]] = m[2];
    return '';
  });
  const tokens = marked.lexer(body, { gfm: true });
  let title = meta['title'] ?? '';
  if (!title) {
    const h = tokens.find((t) => t.type === 'heading') as { text?: string } | undefined;
    title = h?.text?.replace(/[#\s]+/g, ' ').trim() || rel.replace(/\.md$/, '');
  }
  const cert = meta['cert'] === 'hitl' || meta['cert'] === 'human' ? meta['cert'] : null;
  return {
    path: rel,
    name: rel.replace(/\.md$/, ''),
    title,
    summary: meta['summary'] ?? '',
    date: meta['date'] ?? '',
    cert,
    tokens,
  };
}

function collect(): string[] {
  const out: string[] = [];
  const walk = (dir: string, prefix: string) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (e.isDirectory()) walk(path.join(dir, e.name), `${prefix}${e.name}/`);
      else if (e.name.endsWith('.md')) out.push(`${prefix}${e.name}`);
    }
  };
  walk(CONTENT_DIR, '');
  return out;
}

export function generateContent(): void {
  const docs = collect().map(parseDoc);
  const banner =
    `// GENERATED by scripts/build-content.ts — do not edit by hand.\n` +
    `// Edit content/*.md instead. Generated: ${new Date().toISOString()}\n\n` +
    `export interface DocMeta {\n` +
    `  path: string; name: string; title: string; summary: string; date: string;\n` +
    `  cert: 'human' | 'hitl' | null; tokens: unknown[];\n` +
    `}\n\n` +
    `export const DOCS: DocMeta[] = ${JSON.stringify(docs, null, 1)};\n`;
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner);
  console.log(`[content] ${docs.length} docs -> src/generated/content.ts`);
}

if (process.argv[1] && process.argv[1].endsWith('build-content.ts')) generateContent();
